### PR TITLE
Fix addEventListener type of mapkit.Annotation

### LINKED ISSUE #1: addEventListener with strict type checking
First of all I wanted to say thank you for making this, it's awesome.

In `mapkit.Annotation.d.ts` there is: 

```
* @param listener The callback function to invoke. listener is passed an
* annotation event as its sole argument.

  addEventListener<K extends keyof AnnotationEvents<this>>(
      type: K,
      listener: () => void,
      thisObject?: object,
    ): void;
```

When I pass an object to a listener:
```
  newMarker.addEventListener('select', (event: mapkit.EventBase<mapkit.MarkerAnnotation>) => {
      const myAnnotation = event.target;
      console.log('Clicked');
    });
```
It errors that `(event: ...) => void` is not assignable to `() => void`.

Would it be better to declare the addEventListener as:

```
    addEventListener<K extends keyof AnnotationEvents<this>>(
      type: K,
      listener: (event: mapkit.EventBase<any>) => void,
      thisObject?: object,
    ): void;
```

Of note, I'm sure there is something better than any to put in there.

### PR DESCRIPTION
**Pull request by wsmd**
Fixes #1

### CODE REVIEW

File: mapkit/mapkit.Annotation.d.ts [hunk 1]
```diff
@@ -380,12 +380,5 @@ declare namespace mapkit {
     titleVisibility?: string;
   }
 
-  // prettier-ignore
-  interface AnnotationEvents<T> {
-    'select': EventBase<T> & { annotation: Annotation; overlay: Overlay };
-    'deselect': EventBase<T> & { annotation: Annotation; overlay: Overlay };
-    'drag-start': EventBase<T> & { annotation: Annotation };
-    'dragging': EventBase<T> & { annotation: Annotation; coordinate: Coordinate };
-    'drag-end': EventBase<T> & { annotation: Annotation };
```
Comment (wsmd) [inline mapkit/mapkit.Annotation.d.ts]: Those turned out to be `Map` events related to an `Annotation`, and not meant to be used on the `Annotation` itself.

```ts
map.addEventListner('drag-start', event => {
  event.annoation // good
});

annotation.addEventListner('drag-start', event => {
  event.annoation // bad
});
```

File: mapkit/mapkit.Annotation.d.ts [hunk 2]
```diff
@@ -44,9 +44,9 @@ declare namespace mapkit {
      * @param thisObject An object to be set as the this keyword on the listener
      * function.
      */
-    removeEventListener<K extends keyof AnnotationEvents<this>>(
-      type: K,
-      listener: () => void,
+    removeEventListener(
+      type: AnnotationEvent,
+      listener: (event: EventBase<Map>) => void,
```
Comment (wsmd) [inline mapkit/mapkit.Annotation.d.ts]: `event.target` turns out to be `Map` not `this`/`Annotation`

**Comment by EricKit** [comment]
I updated, and I have no type issues with my code. Thanks again!!
